name: cognidetect
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Responsive UI
  sizer: ^2.0.15

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  percent_indicator: ^4.2.3
  sign_in_button: ^3.2.0

  # Connectivity & Utilities
  connectivity_plus: ^6.0.5
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  share_plus: ^10.0.2

  # Camera & Media (⚠️ limited on Web)
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  record: ^5.1.2

  # Storage & Files
  path_provider: ^2.1.4
  pdf: ^3.11.0
  universal_html: ^2.2.4

  # Charts
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
